TARGET = scraper.exe

SRC_DIR = src
BIN_DIR = bin
OBJ_DIR = obj

CC=x86_64-w64-mingw32-gcc-4.5.4-release-win64_rubenvb/mingw64/bin/gcc
CFLAGS=-I. -L$(BIN_DIR) -std=c99
LIBS = -l:libcurl.dll -l:sqlite3.dll -l:libcrypto-1_1-x64.dll

all: scraper

scraper:
	$(CC) $(SRC_DIR)/*.c $(CFLAGS) $(LIBS) -o $(BIN_DIR)/$(TARGET)

clean:
	del $(BIN_DIR)\$(TARGET)